/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "lua_thread_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lua_RunScript_call, lua_RunScript_call, AUTO)


PB_BIND(lua_RunScript_reply, lua_RunScript_reply, AUTO)


PB_BIND(lua_GetLastMessage_call, lua_GetLastMessage_call, AUTO)


PB_BIND(lua_GetLastMessage_reply, lua_GetLastMessage_reply, 2)


PB_BIND(lua_LuaCallset, lua_LuaCallset, 2)



