/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "Lfs_PartRpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(lfspart_FileInfo, lfspart_FileInfo, AUTO)


PB_BIND(lfspart_GetFsInfo_call, lfspart_GetFsInfo_call, AUTO)


PB_BIND(lfspart_GetFsInfo_reply, lfspart_GetFsInfo_reply, AUTO)


PB_BIND(lfspart_DirOpen_call, lfspart_DirOpen_call, 2)


PB_BIND(lfspart_DirOpen_reply, lfspart_DirOpen_reply, AUTO)


PB_BIND(lfspart_DirClose_call, lfspart_DirClose_call, AUTO)


PB_BIND(lfspart_DirClose_reply, lfspart_DirClose_reply, AUTO)


PB_BIND(lfspart_DirRead_call, lfspart_DirRead_call, AUTO)


PB_BIND(lfspart_DirRead_reply, lfspart_DirRead_reply, AUTO)


PB_BIND(lfspart_DirList_call, lfspart_DirList_call, 2)


PB_BIND(lfspart_DirList_reply, lfspart_DirList_reply, 2)


PB_BIND(lfspart_LfsCallset, lfspart_LfsCallset, 2)



