/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_LFSPART_LFS_PARTRPC_PB_H_INCLUDED
#define PB_LFSPART_LFS_PARTRPC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _lfspart_FileInfo {
    uint32_t type;
    uint32_t size;
    char name[64];
} lfspart_FileInfo;

typedef struct _lfspart_GetFsInfo_call {
    /* Partition label. */
    char part_label[18];
} lfspart_GetFsInfo_call;

typedef struct _lfspart_GetFsInfo_reply {
    /* Partition address. */
    uint32_t address;
    /* Partition size, bytes. */
    uint32_t size;
    /* Size of a logical block, in bytes. */
    uint32_t block_size;
    /* Number of total blocks */
    uint32_t block_count;
} lfspart_GetFsInfo_reply;

typedef struct _lfspart_DirOpen_call {
    /* Partition label. */
    char part_label[18];
    /* Path to open */
    char path[256];
} lfspart_DirOpen_call;

typedef struct _lfspart_DirOpen_reply {
    /* File descriptor, -1 on error. */
    int32_t fd;
} lfspart_DirOpen_reply;

typedef struct _lfspart_DirClose_call {
    uint32_t fd;
} lfspart_DirClose_call;

typedef struct _lfspart_DirClose_reply {
    char dummy_field;
} lfspart_DirClose_reply;

typedef struct _lfspart_DirRead_call {
    /* File descriptor */
    uint32_t fd;
} lfspart_DirRead_call;

typedef struct _lfspart_DirRead_reply {
    bool valid;
    bool has_info;
    lfspart_FileInfo info;
} lfspart_DirRead_reply;

typedef struct _lfspart_DirList_call {
    /* Partition label. */
    char part_label[18];
    /* Path to open */
    char path[256];
    /* Starting index of reply entry. */
    uint32_t start_idx;
} lfspart_DirList_call;

typedef struct _lfspart_DirList_reply {
    bool valid;
    /* Total entries in directory */
    uint32_t num_entries;
    /* Starting index of entry in info_array, */
    uint32_t start_idx;
    pb_size_t info_array_count;
    lfspart_FileInfo info_array[8];
} lfspart_DirList_reply;

typedef struct _lfspart_LfsCallset {
    pb_size_t which_msg;
    union {
        lfspart_GetFsInfo_call getfsinfo_call;
        lfspart_GetFsInfo_reply getfsinfo_reply;
        lfspart_DirOpen_call diropen_call;
        lfspart_DirOpen_reply diropen_reply;
        lfspart_DirClose_call dirclose_call;
        lfspart_DirClose_reply dirclose_reply;
        lfspart_DirRead_call dirread_call;
        lfspart_DirRead_reply dirread_reply;
        lfspart_DirList_call dirlist_call;
        lfspart_DirList_reply dirlist_reply;
    } msg;
} lfspart_LfsCallset;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define lfspart_FileInfo_init_default            {0, 0, ""}
#define lfspart_GetFsInfo_call_init_default      {""}
#define lfspart_GetFsInfo_reply_init_default     {0, 0, 0, 0}
#define lfspart_DirOpen_call_init_default        {"", ""}
#define lfspart_DirOpen_reply_init_default       {0}
#define lfspart_DirClose_call_init_default       {0}
#define lfspart_DirClose_reply_init_default      {0}
#define lfspart_DirRead_call_init_default        {0}
#define lfspart_DirRead_reply_init_default       {0, false, lfspart_FileInfo_init_default}
#define lfspart_DirList_call_init_default        {"", "", 0}
#define lfspart_DirList_reply_init_default       {0, 0, 0, 0, {lfspart_FileInfo_init_default, lfspart_FileInfo_init_default, lfspart_FileInfo_init_default, lfspart_FileInfo_init_default, lfspart_FileInfo_init_default, lfspart_FileInfo_init_default, lfspart_FileInfo_init_default, lfspart_FileInfo_init_default}}
#define lfspart_LfsCallset_init_default          {0, {lfspart_GetFsInfo_call_init_default}}
#define lfspart_FileInfo_init_zero               {0, 0, ""}
#define lfspart_GetFsInfo_call_init_zero         {""}
#define lfspart_GetFsInfo_reply_init_zero        {0, 0, 0, 0}
#define lfspart_DirOpen_call_init_zero           {"", ""}
#define lfspart_DirOpen_reply_init_zero          {0}
#define lfspart_DirClose_call_init_zero          {0}
#define lfspart_DirClose_reply_init_zero         {0}
#define lfspart_DirRead_call_init_zero           {0}
#define lfspart_DirRead_reply_init_zero          {0, false, lfspart_FileInfo_init_zero}
#define lfspart_DirList_call_init_zero           {"", "", 0}
#define lfspart_DirList_reply_init_zero          {0, 0, 0, 0, {lfspart_FileInfo_init_zero, lfspart_FileInfo_init_zero, lfspart_FileInfo_init_zero, lfspart_FileInfo_init_zero, lfspart_FileInfo_init_zero, lfspart_FileInfo_init_zero, lfspart_FileInfo_init_zero, lfspart_FileInfo_init_zero}}
#define lfspart_LfsCallset_init_zero             {0, {lfspart_GetFsInfo_call_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define lfspart_FileInfo_type_tag                1
#define lfspart_FileInfo_size_tag                2
#define lfspart_FileInfo_name_tag                3
#define lfspart_GetFsInfo_call_part_label_tag    1
#define lfspart_GetFsInfo_reply_address_tag      1
#define lfspart_GetFsInfo_reply_size_tag         2
#define lfspart_GetFsInfo_reply_block_size_tag   3
#define lfspart_GetFsInfo_reply_block_count_tag  4
#define lfspart_DirOpen_call_part_label_tag      1
#define lfspart_DirOpen_call_path_tag            2
#define lfspart_DirOpen_reply_fd_tag             1
#define lfspart_DirClose_call_fd_tag             1
#define lfspart_DirRead_call_fd_tag              1
#define lfspart_DirRead_reply_valid_tag          1
#define lfspart_DirRead_reply_info_tag           2
#define lfspart_DirList_call_part_label_tag      1
#define lfspart_DirList_call_path_tag            2
#define lfspart_DirList_call_start_idx_tag       3
#define lfspart_DirList_reply_valid_tag          1
#define lfspart_DirList_reply_num_entries_tag    2
#define lfspart_DirList_reply_start_idx_tag      3
#define lfspart_DirList_reply_info_array_tag     4
#define lfspart_LfsCallset_getfsinfo_call_tag    1
#define lfspart_LfsCallset_getfsinfo_reply_tag   2
#define lfspart_LfsCallset_diropen_call_tag      3
#define lfspart_LfsCallset_diropen_reply_tag     4
#define lfspart_LfsCallset_dirclose_call_tag     5
#define lfspart_LfsCallset_dirclose_reply_tag    6
#define lfspart_LfsCallset_dirread_call_tag      7
#define lfspart_LfsCallset_dirread_reply_tag     8
#define lfspart_LfsCallset_dirlist_call_tag      9
#define lfspart_LfsCallset_dirlist_reply_tag     10

/* Struct field encoding specification for nanopb */
#define lfspart_FileInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   size,              2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3)
#define lfspart_FileInfo_CALLBACK NULL
#define lfspart_FileInfo_DEFAULT NULL

#define lfspart_GetFsInfo_call_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   part_label,        1)
#define lfspart_GetFsInfo_call_CALLBACK NULL
#define lfspart_GetFsInfo_call_DEFAULT NULL

#define lfspart_GetFsInfo_reply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   SINGULAR, UINT32,   size,              2) \
X(a, STATIC,   SINGULAR, UINT32,   block_size,        3) \
X(a, STATIC,   SINGULAR, UINT32,   block_count,       4)
#define lfspart_GetFsInfo_reply_CALLBACK NULL
#define lfspart_GetFsInfo_reply_DEFAULT NULL

#define lfspart_DirOpen_call_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   part_label,        1) \
X(a, STATIC,   SINGULAR, STRING,   path,              2)
#define lfspart_DirOpen_call_CALLBACK NULL
#define lfspart_DirOpen_call_DEFAULT NULL

#define lfspart_DirOpen_reply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    fd,                1)
#define lfspart_DirOpen_reply_CALLBACK NULL
#define lfspart_DirOpen_reply_DEFAULT NULL

#define lfspart_DirClose_call_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   fd,                1)
#define lfspart_DirClose_call_CALLBACK NULL
#define lfspart_DirClose_call_DEFAULT NULL

#define lfspart_DirClose_reply_FIELDLIST(X, a) \

#define lfspart_DirClose_reply_CALLBACK NULL
#define lfspart_DirClose_reply_DEFAULT NULL

#define lfspart_DirRead_call_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   fd,                1)
#define lfspart_DirRead_call_CALLBACK NULL
#define lfspart_DirRead_call_DEFAULT NULL

#define lfspart_DirRead_reply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     valid,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              2)
#define lfspart_DirRead_reply_CALLBACK NULL
#define lfspart_DirRead_reply_DEFAULT NULL
#define lfspart_DirRead_reply_info_MSGTYPE lfspart_FileInfo

#define lfspart_DirList_call_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   part_label,        1) \
X(a, STATIC,   SINGULAR, STRING,   path,              2) \
X(a, STATIC,   SINGULAR, UINT32,   start_idx,         3)
#define lfspart_DirList_call_CALLBACK NULL
#define lfspart_DirList_call_DEFAULT NULL

#define lfspart_DirList_reply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     valid,             1) \
X(a, STATIC,   SINGULAR, UINT32,   num_entries,       2) \
X(a, STATIC,   SINGULAR, UINT32,   start_idx,         3) \
X(a, STATIC,   REPEATED, MESSAGE,  info_array,        4)
#define lfspart_DirList_reply_CALLBACK NULL
#define lfspart_DirList_reply_DEFAULT NULL
#define lfspart_DirList_reply_info_array_MSGTYPE lfspart_FileInfo

#define lfspart_LfsCallset_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,getfsinfo_call,msg.getfsinfo_call),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,getfsinfo_reply,msg.getfsinfo_reply),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,diropen_call,msg.diropen_call),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,diropen_reply,msg.diropen_reply),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,dirclose_call,msg.dirclose_call),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,dirclose_reply,msg.dirclose_reply),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,dirread_call,msg.dirread_call),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,dirread_reply,msg.dirread_reply),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,dirlist_call,msg.dirlist_call),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,dirlist_reply,msg.dirlist_reply),  10)
#define lfspart_LfsCallset_CALLBACK NULL
#define lfspart_LfsCallset_DEFAULT NULL
#define lfspart_LfsCallset_msg_getfsinfo_call_MSGTYPE lfspart_GetFsInfo_call
#define lfspart_LfsCallset_msg_getfsinfo_reply_MSGTYPE lfspart_GetFsInfo_reply
#define lfspart_LfsCallset_msg_diropen_call_MSGTYPE lfspart_DirOpen_call
#define lfspart_LfsCallset_msg_diropen_reply_MSGTYPE lfspart_DirOpen_reply
#define lfspart_LfsCallset_msg_dirclose_call_MSGTYPE lfspart_DirClose_call
#define lfspart_LfsCallset_msg_dirclose_reply_MSGTYPE lfspart_DirClose_reply
#define lfspart_LfsCallset_msg_dirread_call_MSGTYPE lfspart_DirRead_call
#define lfspart_LfsCallset_msg_dirread_reply_MSGTYPE lfspart_DirRead_reply
#define lfspart_LfsCallset_msg_dirlist_call_MSGTYPE lfspart_DirList_call
#define lfspart_LfsCallset_msg_dirlist_reply_MSGTYPE lfspart_DirList_reply

extern const pb_msgdesc_t lfspart_FileInfo_msg;
extern const pb_msgdesc_t lfspart_GetFsInfo_call_msg;
extern const pb_msgdesc_t lfspart_GetFsInfo_reply_msg;
extern const pb_msgdesc_t lfspart_DirOpen_call_msg;
extern const pb_msgdesc_t lfspart_DirOpen_reply_msg;
extern const pb_msgdesc_t lfspart_DirClose_call_msg;
extern const pb_msgdesc_t lfspart_DirClose_reply_msg;
extern const pb_msgdesc_t lfspart_DirRead_call_msg;
extern const pb_msgdesc_t lfspart_DirRead_reply_msg;
extern const pb_msgdesc_t lfspart_DirList_call_msg;
extern const pb_msgdesc_t lfspart_DirList_reply_msg;
extern const pb_msgdesc_t lfspart_LfsCallset_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lfspart_FileInfo_fields &lfspart_FileInfo_msg
#define lfspart_GetFsInfo_call_fields &lfspart_GetFsInfo_call_msg
#define lfspart_GetFsInfo_reply_fields &lfspart_GetFsInfo_reply_msg
#define lfspart_DirOpen_call_fields &lfspart_DirOpen_call_msg
#define lfspart_DirOpen_reply_fields &lfspart_DirOpen_reply_msg
#define lfspart_DirClose_call_fields &lfspart_DirClose_call_msg
#define lfspart_DirClose_reply_fields &lfspart_DirClose_reply_msg
#define lfspart_DirRead_call_fields &lfspart_DirRead_call_msg
#define lfspart_DirRead_reply_fields &lfspart_DirRead_reply_msg
#define lfspart_DirList_call_fields &lfspart_DirList_call_msg
#define lfspart_DirList_reply_fields &lfspart_DirList_reply_msg
#define lfspart_LfsCallset_fields &lfspart_LfsCallset_msg

/* Maximum encoded size of messages (where known) */
#define lfspart_DirClose_call_size               6
#define lfspart_DirClose_reply_size              0
#define lfspart_DirList_call_size                283
#define lfspart_DirList_reply_size               646
#define lfspart_DirOpen_call_size                277
#define lfspart_DirOpen_reply_size               11
#define lfspart_DirRead_call_size                6
#define lfspart_DirRead_reply_size               81
#define lfspart_FileInfo_size                    77
#define lfspart_GetFsInfo_call_size              19
#define lfspart_GetFsInfo_reply_size             24
#define lfspart_LfsCallset_size                  649

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
