/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "TestRpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(test_Add_call, test_Add_call, AUTO)


PB_BIND(test_Add_reply, test_Add_reply, AUTO)


PB_BIND(test_HandlerError_call, test_HandlerError_call, AUTO)


PB_BIND(test_HandlerError_reply, test_HandlerError_reply, AUTO)


PB_BIND(test_SetStruct_call, test_SetStruct_call, AUTO)


PB_BIND(test_SetStruct_reply, test_SetStruct_reply, AUTO)


PB_BIND(test_TestCallset, test_TestCallset, AUTO)



